version: "3.9"

services:
  backend:
    build: ./Backend
    container_name: hostelsync-backend
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    networks:
      - hostelsync-network

  frontend:
    build: ./Frontend
    container_name: hostelsync-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./Frontend/.env
    depends_on:
      - backend
    networks:
      - hostelsync-network

networks:
  hostelsync-network:
    driver: bridge
